linters:
  disable-all: true
  enable:
    - durationcheck
    - gocritic
    - gofumpt
    - goimports
    - gomodguard
    - govet
    - ineffassign
    - misspell
    - revive
    - staticcheck
    - tenv
    - typecheck
    - unconvert
    - unused
    - lll
    - gosec
    - gosimple
    - gocyclo
    - sloglint
    - tagalign
    - errcheck

linters-settings:
  lll:
    line-length: 120
  gofumpt:
    extra-rules: true
  sloglint:
    kv-only: true
    no-global: all
    context: all
    static-msg: true
    key-naming-case: snake
  errcheck:
    check-type-assertions: true
